'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PermusClient.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;menu&gt;
        '''  &lt;menuItem  name=&quot;currentUser&quot; id=&quot;0&quot; header=&quot;Home&quot; tooltip=&quot;&quot; image=&quot;home.png&quot; expanded=&quot;False&quot;&gt;&lt;/menuItem&gt;
        '''  &lt;menuItem  name=&quot;users&quot; id=&quot;0&quot; header=&quot;Users&quot; tooltip=&quot;&quot; image=&quot;folder_green.png&quot; expanded=&quot;True&quot;&gt;&lt;/menuItem&gt;
        '''  &lt;menuItem  name=&quot;bc&quot; id=&quot;0&quot; header=&quot;Blockchain&quot; tooltip=&quot;&quot; image=&quot;bc.png&quot; expanded=&quot;True&quot;&gt;&lt;/menuItem&gt;
        '''&lt;/menu&gt;.
        '''</summary>
        Friend ReadOnly Property menu_principale() As String
            Get
                Return ResourceManager.GetString("menu_principale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;TransferTransactionPackage&gt;
        '''  &lt;transaction type=&quot;Transfer&quot; transferTransactionType=&quot;PublicTransfer&quot;&gt;
        '''    &lt;blockSerial&gt;0&lt;/blockSerial&gt;
        '''    &lt;serial&gt;0&lt;/serial&gt;
        '''    &lt;timestamp&gt;-62135596800&lt;/timestamp&gt;
        '''    &lt;transferId /&gt;
        '''    &lt;fromSubject&gt;GMNLNA98P10D976K&lt;/fromSubject&gt;
        '''    &lt;toSubject&gt;GMNGPP63P10D976K&lt;/toSubject&gt;
        '''    &lt;message&gt;ogni 4 secondi&lt;/message&gt;
        '''    &lt;coinAmount&gt;0&lt;/coinAmount&gt;
        '''    &lt;signatureFrom&gt;
        '''      &lt;x509CertificateHash /&gt;
        '''      &lt;signature /&gt;
        '''      &lt;timestamp&gt;0&lt;/timestamp&gt;
        '''    &lt;/signatureFrom [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property test_trans() As String
            Get
                Return ResourceManager.GetString("test_trans", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
